name: Windows RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP
      run: |
        net user runneradmin MyPassword123!
        net localgroup administrators runneradmin /add
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Download and Set up Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath .
        .\ngrok.exe authtoken 2JUYINZrKS1QHx8bzCxoZYiQ1ag_6jqGoi6BsS5zVdNzJUdxV

    - name: Start Ngrok Tunnel
      run: .\ngrok.exe tcp 3389

    - name: Keep Alive
      run: timeout /t 999999
